spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useunicode=true&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.blog.pojo
  mapper-locations: classpath:com/blog/mapper/impl/*Mapper.xml
server:
  port: 8081
management:
  security:
  enabled: false
#prometheus配置
info: alen
alenmanagement: endpoints
web: base-path:/actuatoreposure
include: "*"
